### ISSUE TITLE
❤ your readme and the GIF that's shown!

### ISSUE THREAD

**Issue by PySimpleGUI** [tostos5963/PySimpleGUI-Sliding15Puzzle#1]
Thank you so much for including a GIF to your program in your readme!  Everyone likes pictures and a GIF is even better.

I have at tip that you might like.  Nearly all of my programs that have images include them as base64 strings in the .py file itself.  In the PySimpleGUI demo programs you'll find a number of demos that will help convert your images.  There is also a pip installable program called `psgresizer` that will also convert images to base64.

The advantage of using Base64 is that you can give your users 1 file and they'll have everything they need.

I converted your images and placed them into your source file.  You can see the results running in this Trinket:

https://trinket.io/pygame/8c7e2dc6d6
https://pysimplegui.trinket.io/sites/sliding_puzzle

I have not published this code publicly. It's just there for you to see.

Thank you again for this great program!  I'm really impressed.

**Comment by tostos5963** [comment]
Thank you for the instructions on how to convert the images. I have merged it into my source.

**Comment by PySimpleGUI** [comment]
You're quite welcome!  I'm glad you found it helpful.  I was offering information that you may not have known... wasn't implying the way you wrote your code was not good.... it was great!  I'm happy to read you didn't know about this previously and liked it enough to incorporate into your code.

I hope you continue to make PySimpleGUI programs.  This was was excellent!  And I've never seen a sliding puzzle game made using PySimpleGUI.  FUN!  It's nice to see fun things being made along with the serious stuff.

**Comment by tostos5963** [comment]
Your advice was a pleasure. I am publishing this to get this kind of response.
PySimpleGUI is my favorite package. 
I hope to use PySimpleGUI in the future.

(This is the English of translation software, so there may be some mistakes.)

**Comment by PySimpleGUI** [comment]
Your translated messages don't feel translated.  Everything I've seen written by you has been quite clear.  I understand exactly what you're saying... I think I do and they're very positive messages 😉.  They're also really encouraging and motivating.  Thank you for taking the time to write them.

Over the holiday, I have thought a lot about why I like working on this project so much and I think much of it comes from these kinds of conversations and what I learn and see from the PySimpleGUI users.  Thank you for being a part of that experience.  I'm having a lot fun and it sounds like you are too.  "Favorite package" is quite a big compliment.  I'm would be happy if you found it to be "very helpful", and am honored to be on the list of favorites.

I found this repo via the tutorial you wrote:
https://naotoshisami.com/2021/12/pysimplegui-python-gui-sliding-puzzle-15puzzle/

Users teaching other users is something that didn't occur to me initially as something that would happen.  I knew we would share, but I didn't expect actual instruction the way it's happening.  Thank you for being a teacher!
